gpu_id: 5
infer_data: /data/train_data/graph_ranker/CCKS2019_Yih/testset_model_data.txt
best_model_dir_name: /model/rank_model/CCKS2019_Yih_mainPathHead/30_1_42_100/0.9816085885251672_0.8875764258617687_3
score_file: /data/scores/CCKS2019_Yih_test.score